{% set name = "facility-language-server" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FacilityApi/FacilityLanguageServer/archive/v{{ version }}.tar.gz
  sha256: 83a6f3a25ee72e3dcc268ae53e22e28106db3a4be38a80a11cd44f1b92dc96af

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
    - sed
  run:
    - dotnet

test:
  commands:
    - facility-language-server &
    - exe_pid=$!
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM

about:
  home: https://github.com/FacilityApi/FacilityLanguageServer
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Language server for Facility Service Definition documents.
  dev_url: https://github.com/FacilityApi/FacilityLanguageServer

extra:
  recipe-maintainers:
    - danielnachun
