{% set name = "facility-language-server" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/FacilityApi/FacilityLanguageServer/archive/v{{ version }}.tar.gz
  sha256: ac64ae61e08738a112fdefd7024cee1da4a8c6f0239a2a985c5339bbd880e71f

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
    - sed
  run:
    - dotnet

test:
  commands:
    - facility-language-server &
    - exe_pid=$!
    - trap "kill -SIGTERM ${exe_pid}" SIGTERM

about:
  home: https://github.com/FacilityApi/FacilityLanguageServer
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Language server for Facility Service Definition documents.
  dev_url: https://github.com/FacilityApi/FacilityLanguageServer

extra:
  recipe-maintainers:
    - danielnachun
